import VideoCard from "@/src/components/ui/VideoCard";

export default function VideoGallery() {
  return (
    <section className="py-20 px-4 md:px-10 lg:px-14">
      <div className="container mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Left Column */}
          <div>
            <h1 className="mb-6">
              <span className="text-[#102030] dark:text-[#42b3e5] text-sm font-medium uppercase block mb-4">
                Why Choose Our TechGate Auto
              </span>
              <span className="text-4xl inline-block font-bold text-[#005d90] dark:text-white">
                Video Gallery
              </span>
            </h1>
            <p className="border-b border-gray-200 font-normal mb-10 pb-10 leading-relaxed">
              TechGate Auto allows MRI staff to focus on the care of patients
              and efficient MRI room turnaround rather than worrying about
              anyone entering the room and adversely interacting with the
              dangerous magnetic field generated by the magnet.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 gap-y-10">
              {[
                {
                  title: 'Qualified Specialists',
                  desc: 'For Patients: Easy appointment booking, secure health records access',
                },
                {
                  title: 'Modern Equipment',
                  desc: 'For Healthcare Providers: Streamlined patient management, efficient workflows',
                },
                {
                  title: '24-hour Service',
                  desc: 'For Medical Professionals: Advanced diagnostics, collaborative care',
                },
                {
                  title: 'Infinitely Flexible',
                  desc: 'For Healthcare Institutions: Comprehensive management, enhanced patient outcomes',
                },
              ].map((item, i) => (
                <div key={i} className="space-y-3">
                  <h3 className="text-[#6fb43f] dark:text-white font-semibold">
                    {item.title}
                  </h3>
                  <p className="font-normal text-sm">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Right Column */}
          <div className="grid grid-cols-2 gap-5 mt-10 lg:mt-0">
            <div className="flex flex-col text-right gap-5">
              <VideoCard
                videoSrc="/video/TechGate_9-3-2019.mp4"
                thumbnailSrc="/img/ab1.jpg"
                alt="TechGate Auto Video 1"
                tooltip="Watch: MRI Safety Training"
                className="w-[80%] self-end"
              />
              <VideoCard
                videoSrc="/video/TechGate_9-3-2019.mp4"
                thumbnailSrc="/img/ab2.jpg"
                alt="TechGate Auto Video 2"
                tooltip="Watch: Equipment Overview"
                className="w-full"
              />
            </div>
            <div>
              <VideoCard
                videoSrc="/video/TechGate_9-3-2019.mp4"
                thumbnailSrc="/img/ab3.jpg"
                alt="TechGate Auto Video 3"
                tooltip="Watch: Installation Process"
                className="w-full mt-14"
              />
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
