
import GallerySection from '@/src/components/about/GallerySection'
import NewsletterSubscribe from '@/src/components/about/NewsletterSubscribe'
import PremiumServices from '@/src/components/about/PremiumServices'
import TestimonialSection from '@/src/components/about/TestimonialSection'
import WhatWeDoSection from '@/src/components/about/WhatWeDoSection'
import PageHeader from '@/src/components/common/PageHeader'
import Image from 'next/image'

export default function About() {
  return (
    <>
      <PageHeader
        title="About Us"
        backgroundImage="/img/ab1.jpg"
        scrollTargetId="#next-section"
      />

      {/* About Content */}
      <section id="next-section" className="py-20">
        <div className="container mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-10">
            {/* Left Image Section */}
            <div className="flex items-center justify-center w-full relative">
              <Image
                src="/img/ab3.jpg"
                alt="About Us"
                width={700}
                height={500}
                className="w-[70%]"
              />
              <div className="absolute right-0 bottom-0 p-10 bg-[#005d90] leading-relaxed text-3xl text-white font-semibold">
                Trust the <br /> Experts with <br /> Your Safety
              </div>
            </div>

            {/* Right Content Section */}
            <div className="space-y-6 w-full">
              <div>
                <h1 className="mb-6">
                  <span className="text-[#102030] dark:text-[#42b3e5] text-sm font-medium uppercase block mb-4">
                    What we do
                  </span>
                  <span className="text-4xl inline-block font-light text-[#005d90] dark:text-white">
                    TechGate helps reduce <br /> <b className="font-semibold"> your Liability. </b>
                  </span>
                </h1>

                <p className="font-normal leading-relaxed">
                  TechGate Auto allows MRI staff to focus on the care of patients and efficient MRI room turnaround rather than worrying about anyone entering the room and adversely interacting with the dangerous magnetic field generated by the magnet. Easy to use and designed for the MRI environment, TechGate Auto is deployed whenever MRI staff enter or leave the MRI room or via push button remote operation, providing an immediate physical restriction of access to all unscreened or unauthorized individuals.
                </p>

                {/* Feature List */}
                <div className="grid grid-cols-1">
                  <div className="space-y-3 border-b border-gray-200 py-6">
                    <h3 className="text-[#005d90] dark:text-white text-base font-semibold">
                      <span className="text-gray-500 inline-block mr-2">01.</span> Qualified Specialists
                    </h3>
                  </div>
                  <div className="space-y-3 border-b border-gray-200 py-6">
                    <h3 className="text-[#005d90] dark:text-white text-base font-semibold">
                      <span className="text-gray-500 inline-block mr-2">02.</span> Modern Equipment
                    </h3>
                  </div>
                  <div className="space-y-3 py-6">
                    <h3 className="text-[#005d90] dark:text-white text-base font-semibold">
                      <span className="text-gray-500 inline-block mr-2">03.</span> 24-hour Service
                    </h3>
                  </div>
                </div>

                {/* Button */}
                <button className="bg-[#6fb43f] text-white font-medium px-6 py-3 group uppercase border border-[#6fb43f] hover:bg-white hover:text-[#6fb43f]">
                  About Our Service
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      <WhatWeDoSection />
      <PremiumServices />
      <NewsletterSubscribe/>
      <GallerySection/>
      <section className="py-20 bg-[#005d90]">
      <div className="container mx-auto">
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <h2 className="text-white text-4xl font-light leading-tight">
            We Offer Fast, <b className="font-semibold"> Professional and<br /> Exceptional Services</b>
          </h2>
          <div className="flex flex-col sm:flex-row items-center gap-2">
            <button className="bg-white text-[#005d90] font-medium px-6 py-3 uppercase border border-[#005d90] hover:bg-white hover:text-[#005d90] transition-all">
              Make an appointment
            </button>
            <button className="bg-white text-[#005d90] font-medium px-6 py-3 uppercase border border-[#005d90] hover:bg-white hover:text-[#005d90] transition-all">
              Contact Us Online
            </button>
          </div>
        </div>
      </div>
    </section>
      <TestimonialSection/>

    </>
  )
}
