'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';

const FOOTER_DATA = {
  company: {
    logo: '/img/logo-color.png',
    description: 'TechGate Auto allows MRI staff to focus on the care of patients and efficient MRI room turnaround rather than worrying about anyone entering the room and adversely interacting with the dangerous magnetic field generated by the magnet.',
    socials: [
      {
        name: 'Twitter',
        url: '#',
        icon: 'M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z'
      },
      {
        name: 'LinkedIn',
        url: '#',
        icon: 'M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z'
      }
    ]
  },
  quickLinks: [
    { label: 'Home', href: '/' },
    { label: 'About Us', href: '/about' },
    { label: 'Our Services', href: '/services' },
    { label: 'Contact', href: '/contact' }
  ],
  services: [
    'MetalMag Portal',
    'MSDW – FMD',
    'PD240CH-Z4 Handheld Detector',
    'TechGate',
    'PD240CH Handheld Detector'
  ],
  contact: {
    phone: {
      label: 'Phone',
      value: '1-(844)-423-4976',
      href: 'tel:1-844-423-4976'
    },
    email: {
      label: 'Email',
      value: 'info@aegysgroup.com',
      href: 'mailto:info@aegysgroup.com'
    },
    hours: {
      label: 'Office Hours',
      weekday: 'Mon - Fri: 9:00 AM - 6:00 PM',
      emergency: '24/7 Emergency Support'
    }
  },
  newsletter: {
    title: 'Stay Informed with MRI Safety',
    description: 'Stay updated with the latest MRI safety tips, diagnostic imaging insights, and exclusive solutions delivered straight to your inbox.',
    placeholder: 'Enter your email address'
  },
  legal: {
    copyright: '© 2025 Aegys Group. All rights reserved. | Providing Safety Solutions That Make a Difference',
    links: [
      { id: 'privacy', label: 'Privacy Policy', href: '/privacy-policy' },
      { id: 'terms', label: 'Terms of Service', href: '/terms-service' },
      { id: 'cookie', label: 'Cookie Policy', href: '/cookie-policy' },
      { id: 'sitemap', label: 'Sitemap', href: '/sitemap' }
    ]
  }
};

const ICONS = {
  checkmark: 'M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z',
  phone: 'M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z',
  email: 'M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z',
  location: 'M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z',
  arrowUp: 'M5 10l7-7m0 0l7 7m-7-7v18'
};

export default function Footer() {
  const [email, setEmail] = useState('');
  const [showBackToTop, setShowBackToTop] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setShowBackToTop(window.scrollY > 300);
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const handleSubscribe = () => {
    if (email) {
      console.log('Subscribing email:', email);
      alert('Thank you for subscribing!');
      setEmail('');
    }
  };

  return (
    <footer className="bg-[#005d90] text-white">
      {/* Main Footer Content */}
      <div className="container mx-auto py-16 px-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          
          {/* Company Info */}
          <div className="space-y-6">
            <div className="flex items-center gap-3">
              <Image 
                src={FOOTER_DATA.company.logo}
                alt="Aegys Logo" 
                width={120} 
                height={32}
                className="h-8 w-auto brightness-0 invert"
              />
            </div>
            <p className="text-gray-300 leading-relaxed">
              {FOOTER_DATA.company.description}
            </p>
            <div className="flex space-x-4">
              {FOOTER_DATA.company.socials.map((social) => (
                <a 
                  key={social.name}
                  href={social.url}
                  className="w-10 h-10 bg-[#42b3e5] rounded-full flex items-center justify-center hover:bg-white hover:text-[#005d90] transition-all duration-300"
                  aria-label={social.name}
                >
                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d={social.icon}/>
                  </svg>
                </a>
              ))}
            </div>
          </div>

          {/* Quick Links */}
          <div className="space-y-6">
            <h4 className="text-xl font-semibold">Quick Links</h4>
            <ul className="space-y-3">
              {FOOTER_DATA.quickLinks.map((link) => (
                <li key={link.href}>
                  <Link href={link.href} className="text-gray-300 hover:text-[#42b3e5] transition-colors duration-300 flex items-center gap-2">
                    <span className="w-1 h-1 bg-[#42b3e5] rounded-full"></span>
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Services */}
          <div className="space-y-6">
            <h4 className="text-xl font-semibold">Our Services</h4>
            <ul className="space-y-3">
              {FOOTER_DATA.services.map((service) => (
                <li key={service}>
                  <a href="#" className="text-gray-300 hover:text-[#42b3e5] transition-colors duration-300 flex items-center gap-2">
                    <svg className="w-4 h-4 text-[#42b3e5]" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d={ICONS.checkmark} clipRule="evenodd"/>
                    </svg>
                    {service}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          {/* Contact Info */}
          <div className="space-y-6">
            <h4 className="text-xl font-semibold">Get In Touch</h4>
            <div className="space-y-4">
              {/* Phone */}
              <div className="flex items-start gap-3">
                <div className="w-6 h-6 bg-[#42b3e5] rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                  <svg className="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
                    <path d={ICONS.phone}/>
                  </svg>
                </div>
                <div>
                  <p className="text-gray-300">{FOOTER_DATA.contact.phone.label}</p>
                  <a href={FOOTER_DATA.contact.phone.href} className="text-white hover:text-[#42b3e5] transition-colors duration-300">
                    {FOOTER_DATA.contact.phone.value}
                  </a>
                </div>
              </div>
              
              {/* Email */}
              <div className="flex items-start gap-3">
                <div className="w-6 h-6 bg-[#42b3e5] rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                  <svg className="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
                    <path d={ICONS.email}/>
                  </svg>
                </div>
                <div>
                  <p className="text-gray-300">{FOOTER_DATA.contact.email.label}</p>
                  <a href={FOOTER_DATA.contact.email.href} className="text-white hover:text-[#42b3e5] transition-colors duration-300">
                    {FOOTER_DATA.contact.email.value}
                  </a>
                </div>
              </div>
              
              {/* Hours */}
              <div className="flex items-start gap-3">
                <div className="w-6 h-6 bg-[#42b3e5] rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                  <svg className="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
                    <path fillRule="evenodd" d={ICONS.location} clipRule="evenodd"/>
                  </svg>
                </div>
                <div>
                  <p className="text-gray-300">{FOOTER_DATA.contact.hours.label}</p>
                  <p className="text-white">{FOOTER_DATA.contact.hours.weekday}</p>
                  <p className="text-white">{FOOTER_DATA.contact.hours.emergency}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Newsletter Section */}
      <div className="border-t border-[#42b3e5]/20 bg-[#030050]">
        <div className="container mx-auto py-12 px-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
            <div>
              <h3 className="text-2xl font-bold mb-3">{FOOTER_DATA.newsletter.title}</h3>
              <p className="text-gray-300">{FOOTER_DATA.newsletter.description}</p>
            </div>
            <div className="flex flex-col sm:flex-row gap-4">
              <input 
                type="email" 
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder={FOOTER_DATA.newsletter.placeholder}
                className="flex-1 px-4 py-3 rounded-lg bg-white/10 border border-[#42b3e5]/30 text-white placeholder-gray-400 focus:ring-2 focus:ring-[#42b3e5] focus:border-transparent transition-all duration-300 outline-none"
              />
              <button 
                onClick={handleSubscribe}
                className="px-6 py-3 bg-gradient-to-r from-[#42b3e5] to-[#2ea3d4] text-white font-semibold rounded-lg hover:shadow-lg transform hover:-translate-y-0.5 transition-all duration-300"
              >
                Subscribe
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Footer */}
      <div className="border-t border-[#42b3e5]/20 bg-[#020040]">
        <div className="container mx-auto py-6 px-4">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div className="text-gray-400 text-sm text-center md:text-left">
              {FOOTER_DATA.legal.copyright}
            </div>
            <div className="flex items-center gap-6 text-sm flex-wrap justify-center">
              {FOOTER_DATA.legal.links.map((link) => (
                <Link 
                  key={link.id}
                  href={link.href}
                  className="text-gray-400 hover:text-[#42b3e5] transition-colors duration-300"
                >
                  {link.label}
                </Link>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Back to Top Button */}
      <button 
        onClick={scrollToTop}
        className={`fixed bottom-8 right-8 w-12 h-12 bg-[#42b3e5] text-white rounded-full shadow-lg hover:bg-[#005d90] transition-all duration-300 transform hover:-translate-y-1 z-50 ${
          showBackToTop ? 'opacity-100 visible' : 'opacity-0 invisible'
        }`}
        aria-label="Back to top"
      >
        <svg className="w-6 h-6 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d={ICONS.arrowUp}/>
        </svg>
      </button>
    </footer>
  );
}